1 ¿Qué diferencia hay entre una Serie y un DataFrame?

Series es unidimensional y DataFrame tiene 2 dimensiones, filas y columnas.
Series tiene un único tipo de dato.

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Dataframes
# 2 Crea un array de dos dimensiones con 4 filas y 3 columnas.

array = np.random.random_sample((4, 3))

In [5]:
# Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df_paises = pd.DataFrame(array, columns=["España", "Francia", "Italia"])

df_paises.head()

     España   Francia    Italia
0  0.613254  0.777813  0.276683
1  0.402571  0.989863  0.596402
2  0.948480  0.772730  0.768088
3  0.420271  0.000742  0.280461

In [6]:
# Carga el DataFrame medallas.csv

df_medallas = pd.read_csv("medallas.csv", index_col=0)

df_medallas.head(20)

               País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [ ]:
# Usando el loc extrae todas las columnas de la fila de Tailandia.

df_medallas = df_medallas.set_index("País")

KeyError: "None of ['País'] are in the columns"

In [23]:
df_medallas.loc[["Tailandia"]]

           Oro  Plata  Bronce
País
Tailandia  132    175     278

In [24]:
# Usando el loc extrae todas las columnas de China e Irán.

df_medallas.loc[["China", "Irán"]]

        Oro  Plata  Bronce
País
China  1473    994     720
Irán    179    181     197

In [ ]:
# Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

df_medallas.loc[["China", "Irán"]]

In [ ]:
# Usando el iloc extrae la información de la India. Devolved todas las columnas.

df_medallas.iloc[[5]]

       Oro  Plata  Bronce
País
India  154    202     315

In [27]:
# Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

df_medallas.iloc[1::2]

                  Oro  Plata  Bronce
País
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

In [ ]:
# Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

df_medallas.iloc[1::2]

In [28]:
# ¿Qué país consiguió más de 200 medallas de oro?

paises_oro = df_medallas[df_medallas["Oro"] > 200]

paises_oro

                Oro  Plata  Bronce
País
China          1473    994     720
Japón          1032   1037     985
Corea del Sur   745    663     827

In [31]:
# ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

paises_oro_plata = df_medallas[(df_medallas["Oro"] > 200) & (df_medallas["Plata"] > 1000)]

paises_oro_plata

        Oro  Plata  Bronce
País
Japón  1032   1037     985

In [32]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

paises_oro_bronce = df_medallas[(df_medallas["Oro"] > 200) | (df_medallas["Bronce"] > 700)]

paises_oro_bronce

                Oro  Plata  Bronce
País
China          1473    994     720
Japón          1032   1037     985
Corea del Sur   745    663     827

In [ ]:
# Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

df_medallas.insert(3, "total", (df_medallas["Oro"] + df_medallas["Plata"] + df_medallas["Bronce"]))

ValueError: cannot insert total, already exists

In [40]:
df_medallas.head()

                Oro  Plata  Bronce  total
País
China          1473    994     720   3187
Japón          1032   1037     985   3054
Corea del Sur   745    663     827   2235
Irán            179    181     197    557
Kazajistán      155    158     224    537

In [ ]:
# SERIES
# 3 Crea dos listas: Una que se llame "valores" que tenga 7 números aleatorios. Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

valores = pd.Series(range(1, 8))

print(valores)

indices = pd.Series(["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"])

print(indices)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64
0        Lunes
1       Martes
2    Miércoles
3       Jueves
4      Viernes
5       Sábado
6      Domingo
dtype: str

In [46]:
# A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

valores.index = indices

print(valores)

Lunes        1
Martes       2
Miércoles    3
Jueves       4
Viernes      5
Sábado       6
Domingo      7
dtype: int64

In [ ]:
# A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más información sobre este método aquí.

diccionario_vacio = {}

for valor, indice in zip(valores, indices):
    diccionario_vacio[valor] = indice

print(diccionario_vacio)

# Con zip recorremos dos listas y las unimos al mismo tiempo

{1: 'Lunes', 2: 'Martes', 3: 'Miércoles', 4: 'Jueves', 5: 'Viernes', 6: 'Sábado', 7: 'Domingo'}

In [ ]:
# Crea una Serie con el diccionario creado en el punto anterior. ¿Qué forma tiene esta última Serie?

diccionario = pd.Series(diccionario_vacio)

diccionario.head(7)

# Los índices son de tipo string

1        Lunes
2       Martes
3    Miércoles
4       Jueves
5      Viernes
6       Sábado
7      Domingo
dtype: str