Tienes a tu disposición dos conjuntos de datos, "world-data-2023-part1.csv" y "world-data-2023-part2.csv", que contienen información de una serie de indicadores y datos de distintos países. Tu tarea es explorar estos conjuntos de datos y determinar qué tienen en común en términos de columnas y datos.

Luego, debes crear un nuevo DataFrame que combine la información de ambos conjuntos de datos en un solo conjunto de datos. Para hacerlo, debes seleccionar el método de unión de Pandas que consideres más apropiado para esta situación y justificar por qué crees que ese método es el mejor en tu informe.

Asegúrate de realizar los siguientes pasos:

- Explora y carga ambos conjuntos de datos en pandas DataFrames.
- Identifica las columnas comunes entre los dos conjuntos de datos.
- Utiliza el método de unión de Pandas que consideres más adecuado para combinar los datos de ambos años en un solo DataFrame.
- Explica por qué elegiste ese método de unión y cómo se llevaron a cabo los pasos anteriores.

In [12]:
import pandas as pd
import numpy as np


pd.set_option('display.max_columns', None)

In [6]:
df_world_data1 = pd.read_csv("files/world-data-2023_part1.csv", index_col=0)
df_world_data1.head(2)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36

In [7]:
df_world_data2 = pd.read_csv("files/world-data-2023_part2.csv", index_col=0)
df_world_data2.head(2)

,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"

In [8]:
df_world_data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                195 non-null    str
 1   Density
(P/Km2)        195 non-null    str
 2   Abbreviation           188 non-null    str
 3   Agricultural Land( %)  188 non-null    str
 4   Land Area(Km2)         194 non-null    str
 5   Armed Forces size      171 non-null    str
 6   Birth Rate             189 non-null    float64
 7   Calling Code           194 non-null    float64
 8   Capital/Major City     192 non-null    str
 9   Co2-Emissions          188 non-null    str
 10  CPI                    178 non-null    str
 11  CPI Change (%)         179 non-null    str
 12  Currency-Code          180 non-null    str
 13  Fertility Rate         188 non-null    float64
 14  Forested Area (%)      188 non-null    str
 15  Gasoline Price         175 non-null    str
dtypes: float64(3), str(13)
memory usage: 24.5 KB

In [9]:
df_world_data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 19 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   GDP                                        193 non-null    str
 1   Gross primary education enrollment (%)     188 non-null    str
 2   Gross tertiary education enrollment (%)    183 non-null    str
 3   Infant mortality                           189 non-null    float64
 4   Largest city                               189 non-null    str
 5   Life expectancy                            187 non-null    float64
 6   Maternal mortality ratio                   181 non-null    float64
 7   Minimum wage                               150 non-null    str
 8   Official language                          190 non-null    str
 9   Out of pocket health expenditure           188 non-null    str
 10  Physicians per thousand                    188 non-null    float64
 11  Population                                 194 non-null    str
 12  Population: Labor force participation (%)  176 non-null    str
 13  Tax revenue (%)                            169 non-null    str
 14  Total tax rate                             183 non-null    str
 15  Unemployment rate                          176 non-null    str
 16  Urban_population                           190 non-null    str
 17  country                                    195 non-null    str
 18  coordinates                                195 non-null    str
dtypes: float64(4), str(15)
memory usage: 29.1 KB

Hemos visualizado ambos ficheros csv. 
Ambas tienen diferente número de columnas, pero mismo número de filas. 
Ambos ficheros tienen el común la columna Country y están en el mismo idioma. Vamos a realizar la unión a través de esta columna.

In [14]:
df_world_data = pd.merge(df_world_data1,df_world_data2,left_on ="Country",right_on="country")

In [15]:
df_world_data.head(2)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"

In [ ]:
round(df_world_data.isnull().sum()/df_world_data.shape[0]*100, 2)

# Realizamos el conteo de nulos. La columna con mayor % es Minimum wage

Country                                       0.00
Density\n(P/Km2)                              0.00
Abbreviation                                  3.59
Agricultural Land( %)                         3.59
Land Area(Km2)                                0.51
Armed Forces size                            12.31
Birth Rate                                    3.08
Calling Code                                  0.51
Capital/Major City                            1.54
Co2-Emissions                                 3.59
CPI                                           8.72
CPI Change (%)                                8.21
Currency-Code                                 7.69
Fertility Rate                                3.59
Forested Area (%)                             3.59
Gasoline Price                               10.26
GDP                                           1.03
Gross primary education enrollment (%)        3.59
Gross tertiary education enrollment (%)       6.15
Infant mortality                              3.08
Largest city                                  3.08
Life expectancy                               4.10
Maternal mortality ratio                      7.18
Minimum wage                                 23.08
Official language                             2.56
Out of pocket health expenditure              3.59
Physicians per thousand                       3.59
Population                                    0.51
Population: Labor force participation (%)     9.74
Tax revenue (%)                              13.33
Total tax rate                                6.15
Unemployment rate                             9.74
Urban_population                              2.56
country                                       0.00
coordinates                                   0.00
dtype: float64

In [ ]:
df_world_data["Minimum wage"]

# Visualizamos la columna Minimum wage. Es el nivel de salario mínimo en moneda local. Entendemos que el % de nulos se debe a que muchos países no tienen un salario mínimo definido. No nos preocupa el % de nulos.

0      $0.43
1      $1.12
2      $0.95
3      $6.63
4      $0.71
        ...
190    $0.01
191    $0.73
192       NaN
193    $0.24
194       NaN
Name: Minimum wage, Length: 195, dtype: str

In [ ]:
round(df_world_data.duplicated().sum()/df_world_data.shape[0]*100, 2)

# No tenemos filas duplicadas

np.float64(0.0)

In [ ]:
# EJERCICIOS DE LIMPIEZA
# 1 Después de la unión de datos, tenemos dos columnas de "country". Elimina una de ellas.

df_world_data.drop(["country"], axis=1, inplace=True)

In [ ]:
df_world_data.head()

# Mostramos el DataFrame para verificar que se ha eliminado correctamente

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51,"$3,154,057,987",106.40%,NaN,2.7,Andorra la Vella,NaN,NaN,$6.63,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97,"$94,635,415,870",113.50%,9.30%,51.6,Luanda,60.8,241.0,$0.71,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"

2 Los nombres de las columnas no son homogeneos. Cambia los nombres de las columnas de tal forma que:

- No tengan espacios.
- Estén en minúscula.
- No tengan paréntesis, es decir, quitar "(%)", "(Km2)".
- Algunas columnas tiene "\n". Eliminalos de los nombres de las columnas.
- Algunas columnas tienen ":". Eliminalos de los nombres de las columnas.

In [ ]:
df_world_data.columns = (df_world_data.columns
                         .str.lower()
                         .str.replace(r"\(p/km2\)|\(km2\)|[()%]", "", regex=True)
                         .str.replace("density\np/", "density")
                         .str.replace("\n", "")
                         .str.replace(":","")
                         .str.strip() # strip() elimina espacios sobrantes al inicio/final
                         .str.replace(" ", "_")) # Opcional: cambia espacios por guiones bajos

In [39]:
df_world_data.head(1)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"

In [43]:
# 3 La columnas coordinates tiene la latitud y la longitud en una sola columna. Crea dos columnas nuevas, una con la longitud y otra con la latitud. Una vez hecho, elimina la columna de coordinates.

df_world_data[["latitude", "longitude"]] = df_world_data["coordinates"].str.split(",", expand=True)

df_world_data.drop(["coordinates"], axis= 1, inplace=True)

In [44]:
df_world_data.head(1)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",('33.93911 ','67.709953')